# Generated by Django 4.2.24 on 2025-12-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursebuilder', '0003_assignment_quiz_userprogress_completed_assignments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outline_score',
            field=models.IntegerField(default=0, help_text='Outline quality score (0-100)'),
        ),
    ]
