# Generated by Django 4.2.24 on 2026-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursebuilder', '0004_course_outline_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_predefined',
            field=models.BooleanField(default=False),
        ),
    ]
